   name: PR Verify

   on:
     pull_request:
       branches: ["main"]
     workflow_dispatch: # Makes that you can trigger this in Github UI

   jobs:
     build:
       name: PR Verify
       uses: ./.github/workflows/reusable-build.yml
       with:
         dotnet_version: 9.0.x

